export type ActionType = 'Accept' | 'Modify' | 'Replace' | 'Add' | 'Edit' | 'Remove' | 'Defer';

export type AuditStatus = 'completed' | 'failed' | 'warning' | 'running';

export interface AuditEntry {
  id: string;
  runNumber: number;
  project: string;
  status: AuditStatus;
  stages: number;
  duration: string;
  durationSeconds: number;
  startedAt: Date;
  actionType: ActionType;
  stage: number;
  nodeType: string;
  nodeName: string;
  user: string;
  reason?: string;
  before?: string;
  after?: string;
  impact?: string;
}

export interface Checkpoint {
  id: string;
  name: string;
  stage: number;
  timestamp: Date;
  description: string;
  entriesCount: number;
}

export const ACTION_TYPES: ActionType[] = ['Accept', 'Modify', 'Replace', 'Add', 'Edit', 'Remove', 'Defer'];

export const ACTION_COLORS: Record<ActionType, string> = {
  Accept: '#39FF14',
  Modify: '#FFB800',
  Replace: '#7B2FFF',
  Add: '#00F5FF',
  Edit: '#00D4E5',
  Remove: '#FF3366',
  Defer: '#4A6487',
};

export const STATUS_CONFIG: Record<AuditStatus, { label: string; color: string }> = {
  completed: { label: 'Completed', color: '#39FF14' },
  failed: { label: 'Failed', color: '#FF3366' },
  warning: { label: 'Warning', color: '#FFB800' },
  running: { label: 'In Progress', color: '#00F5FF' },
};

export const auditEntries: AuditEntry[] = [
  {
    id: '1',
    runNumber: 42,
    project: 'E-Commerce Platform',
    status: 'completed',
    stages: 8,
    duration: '4m 12s',
    durationSeconds: 252,
    startedAt: new Date(Date.now() - 2 * 60 * 1000),
    actionType: 'Accept',
    stage: 3,
    nodeType: 'Actor',
    nodeName: 'PaymentGateway',
    user: 'sarah.chen',
    reason: 'Actor meets all acceptance criteria for payment processing flow',
    before: 'Status: Pending Review\nConfidence: 72%',
    after: 'Status: Accepted\nConfidence: 94%',
    impact: 'Enables checkout flow progression to Stage 4',
  },
  {
    id: '2',
    runNumber: 41,
    project: 'Task Manager App',
    status: 'completed',
    stages: 8,
    duration: '3m 45s',
    durationSeconds: 225,
    startedAt: new Date(Date.now() - 60 * 60 * 1000),
    actionType: 'Modify',
    stage: 2,
    nodeType: 'Capability',
    nodeName: 'TaskAssignment',
    user: 'alex.kim',
    reason: 'Need to add priority scoring to task assignment logic',
    before: 'assignee: userId\npriority: flat',
    after: 'assignee: userId\npriority: scored\nscoreField: urgency',
    impact: 'Improves task routing accuracy by 23%',
  },
  {
    id: '3',
    runNumber: 40,
    project: 'Social API Gateway',
    status: 'warning',
    stages: 7,
    duration: '6m 20s',
    durationSeconds: 380,
    startedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    actionType: 'Replace',
    stage: 5,
    nodeType: 'UseCase',
    nodeName: 'UserAuthentication',
    user: 'morgan.lee',
    reason: 'OAuth2 flow replacing legacy basic auth',
    before: 'authType: basic\ntokenFormat: jwt',
    after: 'authType: oauth2\nprovider: generic\ntokenFormat: jwt',
    impact: 'Security posture improved, adds dependency on OAuth provider',
  },
  {
    id: '4',
    runNumber: 39,
    project: 'E-Commerce Platform',
    status: 'failed',
    stages: 4,
    duration: '—',
    durationSeconds: 0,
    startedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    actionType: 'Remove',
    stage: 4,
    nodeType: 'Story',
    nodeName: 'GuestCheckoutFlow',
    user: 'sarah.chen',
    reason: 'Deprecated in favor of registered user flow',
    before: 'flowType: guest\nsteps: 4',
    after: '[REMOVED]',
    impact: 'Simplifies checkout but may reduce conversion by 8%',
  },
  {
    id: '5',
    runNumber: 38,
    project: 'Blog Platform',
    status: 'completed',
    stages: 8,
    duration: '2m 55s',
    durationSeconds: 175,
    startedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    actionType: 'Add',
    stage: 1,
    nodeType: 'Actor',
    nodeName: 'ContentModerator',
    user: 'jordan.park',
    reason: 'New actor for automated content moderation',
    before: '[NEW]',
    after: 'actor: ContentModerator\nrole: automated\ntriggers: [postCreate, commentAdd]',
    impact: 'Adds content safety layer to publishing flow',
  },
  {
    id: '6',
    runNumber: 37,
    project: 'Analytics Dashboard',
    status: 'completed',
    stages: 8,
    duration: '5m 08s',
    durationSeconds: 308,
    startedAt: new Date(Date.now() - 26 * 60 * 60 * 1000),
    actionType: 'Edit',
    stage: 6,
    nodeType: 'Task',
    nodeName: 'DataAggregation',
    user: 'alex.kim',
    reason: 'Update aggregation window from 1h to 15m for real-time metrics',
    before: 'window: 1h\ngranularity: hourly',
    after: 'window: 15m\ngranularity: quarterHourly',
    impact: 'Improves metric freshness, increases compute cost by 15%',
  },
  {
    id: '7',
    runNumber: 36,
    project: 'Social API Gateway',
    status: 'completed',
    stages: 8,
    duration: '3m 33s',
    durationSeconds: 213,
    startedAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
    actionType: 'Defer',
    stage: 2,
    nodeType: 'Capability',
    nodeName: 'RateLimiting',
    user: 'morgan.lee',
    reason: 'Rate limiting needs infrastructure team input on Redis cluster',
    before: 'Status: In Review',
    after: 'Status: Deferred\nblockedBy: infra-team',
    impact: 'Blocks load testing phase until resolved',
  },
  {
    id: '8',
    runNumber: 35,
    project: 'ML Pipeline Service',
    status: 'failed',
    stages: 3,
    duration: '—',
    durationSeconds: 0,
    startedAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
    actionType: 'Modify',
    stage: 3,
    nodeType: 'Actor',
    nodeName: 'ModelTrainer',
    user: 'sarah.chen',
    reason: 'Adjust hyperparameter search space',
    before: 'epochs: 100\nlearningRate: 0.001',
    after: 'epochs: 200\nlearningRate: 0.0005',
    impact: 'Training time doubled, accuracy target may not be met',
  },
  {
    id: '9',
    runNumber: 34,
    project: 'Blog Platform',
    status: 'completed',
    stages: 8,
    duration: '4m 45s',
    durationSeconds: 285,
    startedAt: new Date(Date.now() - 96 * 60 * 60 * 1000),
    actionType: 'Accept',
    stage: 0,
    nodeType: 'UseCase',
    nodeName: 'RSSFeedGeneration',
    user: 'jordan.park',
    reason: 'Clean implementation with full test coverage',
    before: 'Status: Pending Review',
    after: 'Status: Accepted\nTests: 24/24 passing',
  },
  {
    id: '10',
    runNumber: 33,
    project: 'Task Manager App',
    status: 'warning',
    stages: 6,
    duration: '7m 10s',
    durationSeconds: 430,
    startedAt: new Date(Date.now() - 120 * 60 * 60 * 1000),
    actionType: 'Replace',
    stage: 4,
    nodeType: 'Story',
    nodeName: 'NotificationSystem',
    user: 'alex.kim',
    reason: 'Replace email notifications with unified notification hub',
    before: 'channel: email\ntemplate: basic',
    after: 'channel: unified_hub\nchannels: [inApp, email, push]',
    impact: 'Better UX but adds complexity to notification service',
  },
  {
    id: '11',
    runNumber: 32,
    project: 'E-Commerce Platform',
    status: 'completed',
    stages: 8,
    duration: '3m 22s',
    durationSeconds: 202,
    startedAt: new Date(Date.now() - 144 * 60 * 60 * 1000),
    actionType: 'Add',
    stage: 5,
    nodeType: 'Capability',
    nodeName: 'InventoryCheck',
    user: 'sarah.chen',
    reason: 'Add real-time inventory validation before payment',
    before: '[NEW]',
    after: 'capability: InventoryCheck\ntype: synchronous\ntimeout: 500ms',
    impact: 'Prevents overselling, adds 200ms to checkout latency',
  },
  {
    id: '12',
    runNumber: 31,
    project: 'Analytics Dashboard',
    status: 'completed',
    stages: 8,
    duration: '4m 01s',
    durationSeconds: 241,
    startedAt: new Date(Date.now() - 168 * 60 * 60 * 1000),
    actionType: 'Edit',
    stage: 7,
    nodeType: 'Task',
    nodeName: 'ChartRendering',
    user: 'jordan.park',
    reason: 'Optimize chart rendering for large datasets',
    before: 'renderMode: canvas\nmaxPoints: 1000',
    after: 'renderMode: webgl\nmaxPoints: 50000\nvirtualization: true',
    impact: '50x improvement in chart load times for large datasets',
  },
  {
    id: '13',
    runNumber: 30,
    project: 'ML Pipeline Service',
    status: 'running',
    stages: 5,
    duration: '12m 30s',
    durationSeconds: 750,
    startedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000),
    actionType: 'Modify',
    stage: 2,
    nodeType: 'Story',
    nodeName: 'DataPreprocessing',
    user: 'morgan.lee',
    reason: 'Add normalization step for numerical features',
    before: 'normalization: none',
    after: 'normalization: minMax\nfeatureRange: [0, 1]',
    impact: 'Expected 5-10% improvement in model convergence',
  },
  {
    id: '14',
    runNumber: 29,
    project: 'Social API Gateway',
    status: 'completed',
    stages: 8,
    duration: '3m 18s',
    durationSeconds: 198,
    startedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    actionType: 'Accept',
    stage: 1,
    nodeType: 'Actor',
    nodeName: 'APIGateway',
    user: 'alex.kim',
    reason: 'Core infrastructure component verified',
    before: 'Status: Draft',
    after: 'Status: Accepted\nVersion: 2.1.0',
  },
  {
    id: '15',
    runNumber: 28,
    project: 'Blog Platform',
    status: 'failed',
    stages: 2,
    duration: '—',
    durationSeconds: 0,
    startedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000),
    actionType: 'Remove',
    stage: 2,
    nodeType: 'Capability',
    nodeName: 'LegacyImport',
    user: 'jordan.park',
    reason: 'Remove WordPress import capability - no longer needed',
    before: 'source: wordpress\nformat: xml',
    after: '[REMOVED]',
    impact: 'Reduces maintenance burden by removing deprecated importer',
  },
  {
    id: '16',
    runNumber: 27,
    project: 'E-Commerce Platform',
    status: 'completed',
    stages: 8,
    duration: '5m 44s',
    durationSeconds: 344,
    startedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
    actionType: 'Add',
    stage: 4,
    nodeType: 'Story',
    nodeName: 'WishlistFeature',
    user: 'sarah.chen',
    reason: 'Add wishlist functionality per product requirements',
    before: '[NEW]',
    after: 'feature: Wishlist\nmaxItems: 100\nsharing: enabled',
    impact: 'Expected 15% increase in user engagement metrics',
  },
  {
    id: '17',
    runNumber: 26,
    project: 'Task Manager App',
    status: 'warning',
    stages: 7,
    duration: '8m 15s',
    durationSeconds: 495,
    startedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
    actionType: 'Defer',
    stage: 6,
    nodeType: 'Task',
    nodeName: 'RealTimeCollaboration',
    user: 'alex.kim',
    reason: 'WebSocket infrastructure not ready for production',
    before: 'transport: websocket\nconflictResolution: crdt',
    after: 'Status: Deferred\nblockedBy: websocket-infra',
    impact: 'Delays real-time collaboration feature by 2 sprints',
  },
  {
    id: '18',
    runNumber: 25,
    project: 'Analytics Dashboard',
    status: 'completed',
    stages: 8,
    duration: '2m 48s',
    durationSeconds: 168,
    startedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    actionType: 'Edit',
    stage: 0,
    nodeType: 'UseCase',
    nodeName: 'DataIngestion',
    user: 'morgan.lee',
    reason: 'Support multi-tenant data isolation',
    before: 'tenantMode: shared\nschema: public',
    after: 'tenantMode: isolated\nschema: perTenant\nrowLevelSecurity: true',
    impact: 'Enables SaaS deployment model for enterprise customers',
  },
];

export const checkpoints: Checkpoint[] = [
  {
    id: 'cp-1',
    name: 'Initial Scaffold',
    stage: 0,
    timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    description: 'Project structure and base pipeline established',
    entriesCount: 3,
  },
  {
    id: 'cp-2',
    name: 'Stage 3 Complete',
    stage: 3,
    timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    description: 'All actors and capabilities defined for core modules',
    entriesCount: 12,
  },
  {
    id: 'cp-3',
    name: 'Pre-Production Review',
    stage: 6,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    description: 'Ready for final validation before deployment pipeline',
    entriesCount: 18,
  },
  {
    id: 'cp-4',
    name: 'Latest Stable',
    stage: 8,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    description: 'Most recent stable checkpoint with all tests passing',
    entriesCount: 18,
  },
];

export function formatRelativeTime(date: Date): string {
  const now = Date.now();
  const diff = now - date.getTime();
  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);

  if (minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes} min ago`;
  if (hours < 24) return `${hours} hour${hours > 1 ? 's' : ''} ago`;
  if (days < 30) return `${days} day${days > 1 ? 's' : ''} ago`;
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export function formatFullDate(date: Date): string {
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}
