"""Repository ports (`Protocol` interfaces) - ports & adapters.

In-memory implementations live in `shared_kernel/infrastructure/in_memory.py`
(the choice confirmed for this pass - see the plan). A future Postgres/S3
adapter only needs to satisfy these Protocols; application code depends on
them, never on a concrete adapter.
"""

from typing import Protocol, runtime_checkable

from bluebox.modules.advisory.scaling.domain.infrastructure_profile import InfrastructureProfile
from bluebox.modules.advisory.tech_stack.domain.tech_stack_profile import TechStackProfile
from bluebox.modules.chat.domain.chat_message import ChatMessage
from bluebox.modules.code_generation.domain.workspace import GeneratedFile, WorkspaceManifest
from bluebox.modules.core_pipeline.domain.project import Project
from bluebox.modules.core_pipeline.domain.state_machine import PipelineOrchestrator
from bluebox.shared_kernel.domain.audit import AuditEvent, Checkpoint, DecisionEntry
from bluebox.shared_kernel.domain.node import Node
from bluebox.shared_kernel.domain.rbac import RBACModel


@runtime_checkable
class ProjectRepository(Protocol):
    def create(self, project: Project) -> Project: ...
    def get(self, project_id: str) -> Project | None: ...
    def list(self) -> list[Project]: ...
    def delete(self, project_id: str) -> None: ...


@runtime_checkable
class NodeRepository(Protocol):
    def add(self, project_id: str, node: Node) -> None: ...
    def get(self, project_id: str, node_id: str) -> Node | None: ...
    def list_by_project(self, project_id: str) -> list[Node]: ...
    def list_by_stage(self, project_id: str, stage: int) -> list[Node]: ...


@runtime_checkable
class SessionRepository(Protocol):
    """One `PipelineOrchestrator` per project."""

    def get_or_create(self, project_id: str) -> PipelineOrchestrator: ...
    def save(self, project_id: str, orchestrator: PipelineOrchestrator) -> None: ...


@runtime_checkable
class DecisionLedgerRepository(Protocol):
    def append(self, project_id: str, entry: DecisionEntry) -> None: ...
    def list(self, project_id: str) -> list[DecisionEntry]: ...
    def get(self, project_id: str, entry_id: str) -> DecisionEntry | None: ...


@runtime_checkable
class AuditTrailRepository(Protocol):
    def append(self, project_id: str, event: AuditEvent) -> None: ...
    def list(self, project_id: str) -> list[AuditEvent]: ...


@runtime_checkable
class ChatRepository(Protocol):
    def append(self, project_id: str, message: ChatMessage) -> None: ...
    def list(self, project_id: str) -> list[ChatMessage]: ...
    def delete(self, project_id: str, message_id: str) -> bool: ...


@runtime_checkable
class CheckpointRepository(Protocol):
    def create(self, project_id: str, checkpoint: Checkpoint) -> None: ...
    def list(self, project_id: str) -> list[Checkpoint]: ...
    def get(self, project_id: str, checkpoint_id: str) -> Checkpoint | None: ...


@runtime_checkable
class WorkspaceRepository(Protocol):
    def save_file(self, project_id: str, generated_file: GeneratedFile) -> None: ...
    def list_files(self, project_id: str) -> list[GeneratedFile]: ...
    def save_manifest(self, project_id: str, manifest: WorkspaceManifest) -> None: ...
    def get_manifest(self, project_id: str) -> WorkspaceManifest | None: ...


@runtime_checkable
class InfrastructureProfileRepository(Protocol):
    def save(self, project_id: str, profile: InfrastructureProfile) -> None: ...
    def get(self, project_id: str) -> InfrastructureProfile | None: ...


@runtime_checkable
class TechStackProfileRepository(Protocol):
    def save(self, project_id: str, profile: TechStackProfile) -> None: ...
    def get(self, project_id: str) -> TechStackProfile | None: ...


@runtime_checkable
class RBACModelRepository(Protocol):
    def save(self, project_id: str, model: RBACModel) -> None: ...
    def get(self, project_id: str) -> RBACModel | None: ...
